definitions:
  app.Response:
    properties:
      data: {}
      msg:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
  description: go-mall 商城后台系统
  license:
    name: apache2
  title: GO-MALL API
  version: "1.0"
paths:
  /:
    delete:
      description: 用户删除
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
    get:
      description: 公众号服务
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
    post:
      description: 用户余额修改
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
    put:
      description: 用户编辑
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /:id:
    delete:
      description: 删除定时任务调度表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
    get:
      description: 获取单个角色
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /addOrSave:
    post:
      description: 商品添加
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /admin/login:
    post:
      description: 注册
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/address:
    get:
      description: 获取列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/address/default/set:
    post:
      description: 设置默认地址
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/address/del:
    post:
      description: 设置默认地址
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/address/edit:
    post:
      description: 添加or更新地址
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/cart/add:
    post:
      description: 添加购物车
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/cart/count:
    get:
      description: 获取数量
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/cart/num:
    post:
      description: 修改购物车数量
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/carts:
    get:
      description: 购物车列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/category:
    get:
      description: 获取树形数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/city_list:
    get:
      description: 获取树形数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/collect/add:
    post:
      description: 添加收藏
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/collect/del:
    post:
      description: 取消收藏
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/collect/user:
    get:
      description: 获取用户收藏
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/getCanvas:
    get:
      description: 获取画布数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order:
    get:
      description: 获取列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/cancel:
    post:
      description: 未支付订单取消
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/comments/:key:
    post:
      description: 订单评价
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/computed/:key:
    post:
      description: 订单计算
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/confirm:
    post:
      description: 订单确认
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/create/:key:
    post:
      description: 订单创建
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/detail/:key:
    get:
      description: 订单详情
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/notify:
    get:
      description: 订单移步支付
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/pay:
    post:
      description: 订单支付
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/order/take:
    post:
      description: 订单收货
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/product/detail/:id:
    get:
      description: 获取商品详情
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/product/hot:
    get:
      description: 获取推荐商品
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/products:
    get:
      description: 获取商品列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/reply/list/:id:
    get:
      description: 获取商品评论列表数据
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /api/v1/userinfo:
    get:
      description: 获取用户信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /build:
    get:
      description: 菜单构建
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /captcha:
    get:
      description: 获取验证码
      responses: {}
      tags:
      - Admin
  /center:
    put:
      description: 用户修改个人信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /exec/:id:
    put:
      description: 执行定时任务调度表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /gen/columns:
    put:
      description: 保存列配置
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /gen/config:
    put:
      description: 保存配置
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /info:
    get:
      description: 获取用户信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /info/:id:
    get:
      description: 获取商品信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /isFormatAttr/:id:
    post:
      description: 商品sku生成
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /login:
    post:
      description: 会员登录
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /logout:
    delete:
      description: 退出登录
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /menu:
    put:
      description: 角色菜单更新
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /onsale/:id:
    post:
      description: 商品上下架
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /register/verify:
    post:
      description: 短信验证码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
  /save/:id:
    post:
      description: 商品规格sku添加
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /stop/:id:
    put:
      description: 停止定时任务调度表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tools/gen/code:
    get:
      description: 代码生产
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tools/gen/columns:
    get:
      description: 获取表的列信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tools/gen/config/:name:
    get:
      description: 获取表的信息
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tools/gen/import:
    post:
      description: 导入数据库表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tools/gen/preview:
    get:
      description: 代码预览
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tools/gen/systables:
    get:
      description: 获取已经导入的表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tools/gen/tables:
    get:
      description: 获取所有表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /tree:
    get:
      description: 菜单树形
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /updateAvatar:
    post:
      description: 用户上传图像
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /updatePass:
    post:
      description: 用户修改密码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Admin
  /upload:
    post:
      description: 上传图像
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      tags:
      - Front API
swagger: "2.0"
